/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mario_block.gltf --transform
Author: Kacey (https://sketchfab.com/Kaves)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mario-mystery-block-fa6684c813d046d49976a92bf6f3ebad
Title: Mario Mystery Block
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function QuestionBlock(props) {
  const { nodes, materials } = useGLTF('/mario_block-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.crate_low_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/mario_block-transformed.glb')
