/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 circle_rug.gltf --transform
Author: Emma-Lie Kamping (https://sketchfab.com/Ellemieke25)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-circle-rug-2482ea3b59a545c7848bde5ecc06da08
Title: Low-Poly Circle Rug
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CircleRug(props) {
  const { nodes, materials } = useGLTF('/circle_rug-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rukh_Rug_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={2} />
    </group>
  )
}

useGLTF.preload('/circle_rug-transformed.glb')
