/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 billboard.gltf --transform
Author: rkmorello (https://sketchfab.com/rkmorello)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/billboard-lowpoly-baadeaf2bab344a4a909f6d3a19375b7
Title: Billboard - Lowpoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Billboard(props) {
  const { nodes, materials } = useGLTF('/billboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.18, 19.51, -6.9]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.07, 0.47, 0.07]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Light} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Black} position={[-0.55, 11.67, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.89, 0.08, 9.25]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.009']} position={[-0.47, 15.13, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.21, 1, 0.43]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} position={[1.38, 18.06, 7.08]} />
    </group>
  )
}

useGLTF.preload('/billboard-transformed.glb')
