/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 photo_frame.gltf --transform
Author: Dylan Dreyer Varsics (https://sketchfab.com/d.varsics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-architecture-photo-frame-33bedcb0e2064a3a97c19658e254af74
Title: 3D Architecture | Photo frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PhotoFrame1(props) {
  const { nodes, materials } = useGLTF('/photo_frame-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes['Box046_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh geometry={nodes['Box046_Material_#350_0'].geometry} material={materials.Material_350} />
            <mesh geometry={nodes.Box046_Frame_0.geometry} material={materials.Frame} />
            <mesh geometry={nodes['Box046_Material_#26_0'].geometry} material={materials.Material_26} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/photo_frame-transformed.glb')
