/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tv2.gltf --transform
Author: Daniyal Malik (https://sketchfab.com/daniyalmalik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/led-tv-014e75456b4e465b9cecd1b136a0312b
Title: Led Tv
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tv2(props) {
  const { nodes, materials } = useGLTF('/tv2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.led_tv_phong1_0.geometry} material={materials.phong1} position={[0.57, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/tv2-transformed.glb')
