/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 square_firetable.gltf --transform
Author: Three Design (https://sketchfab.com/threedesignstudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/td-141-a-original-square-fire-table-194ea8b4dc744392a007a0628748175d
Title: TD-141 - A - Original Square Fire Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SquareFiretable(props) {
  const { nodes, materials } = useGLTF('/square_firetable-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Material2.geometry} material={materials.Color_M08} rotation={[-Math.PI / 2, 0, 0]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/square_firetable-transformed.glb')
