/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 empty_room.gltf --transform
Author: Yao Zhong (https://sketchfab.com/yaoz2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bedroom-empty-wip-56d51ffc593e4c74bc0e4f910bf23568
Title: Bedroom (Empty)  ----> WIP
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EmptyRoom(props) {
  const { nodes, materials } = useGLTF('/empty_room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.29}>
        <mesh geometry={nodes.wall_b_0.geometry} material={materials.Wall_L} scale={[1, 0.82, 1]} />
        <mesh geometry={nodes.wall_l_0.geometry} material={materials.Wall_L} position={[0, 0.36, 0]} />
        <mesh geometry={nodes.wooden_floor_0.geometry} material={materials.Floor} />
        <mesh geometry={nodes.wooden_cover_l_3_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_l_2_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_l_1_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wall_r_0.geometry} material={materials.Wall_L} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_l_curve1_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_l_curve2_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_l_5_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_l_4_0.geometry} material={materials.wood01} position={[0, -0.33, 0]} />
        <mesh geometry={nodes.wooden_cover_r_3_0.geometry} material={materials.wood01} position={[0, 0.36, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.wooden_cover_b_3_0.geometry} material={materials.wood01} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_f_0.geometry} material={materials.wood01} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_r_curve1_0.geometry} material={materials.wood01} position={[0, 0.3, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_r_2_0.geometry} material={materials.wood01} position={[0, 0.3, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_r_1_0.geometry} material={materials.wood01} position={[0, 0.3, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.wooden_cover_b_1_0.geometry} material={materials.wood01} position={[0, 0.3, 0]} rotation={[0, 0, 3.14]} />
        <mesh geometry={nodes.wooden_cover_b_2_0.geometry} material={materials.wood01} position={[0, 0.3, 0]} rotation={[0, 0, 3.14]} />
        <mesh geometry={nodes.wooden_cover_b_curve_0.geometry} material={materials.wood01} position={[0, 0.3, 0]} rotation={[0, 0, 3.14]} />
        <mesh geometry={nodes.windows_frame_0.geometry} material={materials.windows_frame} position={[0, -0.37, 0]} />
        <mesh geometry={nodes.windows_0.geometry} material={materials.windows_frame} position={[-2.21, 1.41, 1.1]} rotation={[0, 0, -Math.PI / 4]} />
        <mesh geometry={nodes.screw_window_L1_0.geometry} material={materials.Root} position={[-2.2, 1.42, 1.3]} />
        <mesh geometry={nodes.screw_window_L2_0.geometry} material={materials.Root} position={[-2.2, 1.42, 0.93]} />
        <mesh geometry={nodes.certain_hanger_0.geometry} material={materials.Root} position={[-2.15, 0.92, 1.54]} scale={[0.8, 1, 1]} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials.Root} position={[-2.12, 0.9, 1.1]} />
        <mesh geometry={nodes.windows001_0.geometry} material={materials.windows_frame} position={[-2.21, 0.39, 1.1]} rotation={[0, 0, Math.PI / 4]} />
      </group>
    </group>
  )
}

useGLTF.preload('/empty_room-transformed.glb')
