/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 goldbar.gltf --transform
Author: NataN (https://sketchfab.com/NataN-0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gold-bar-low-poly-92b6818cb65542d683f3f71d55fe48c3
Title: Gold Bar Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/goldbar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={[259.08, 100, 46.61]} />
      </group>
    </group>
  )
}

useGLTF.preload('/goldbar-transformed.glb')
