/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 gallery_stand_white.gltf --transform
Author: dayoung.ko (https://sketchfab.com/dayoung.ko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gallery-stand-white-2d00e41ff45d41b680771067510957f0
Title: Gallery Stand (White)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gallery_stand_white-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[-85.76, 0.26, 0.57]} scale={[4.29, 0.45, 2.68]} />
    </group>
  )
}

useGLTF.preload('/gallery_stand_white-transformed.glb')
