/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 stop_rail.gltf --transform
Author: Xillute | Dev (https://sketchfab.com/janchristian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stop-rail-2384e20a879747008974b6b46eb75f1c
Title: Stop Rail
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stop_rail-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} position={[-0.42, -0.08, 0.05]} />
      </group>
    </group>
  )
}

useGLTF.preload('/stop_rail-transformed.glb')
