/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 question_block.gltf --transform
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mario-question-block-efac007aa9214bcaaa5bcb2cf23aeb47
Title: Mario Question Block
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/question_block-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.002']} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.002']} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/question_block-transformed.glb')
