/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 glowstick.gltf --transform
Author: Rofnay (https://sketchfab.com/Rofnay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glowstick-cbc7f31c658247219c32b083183513e5
Title: Glowstick
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GlowStick(props) {
  const { nodes, materials } = useGLTF('/glowstick-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_Body_0.geometry} material={materials.Body} position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cylinder001_Glow_0.geometry} material={materials.Glow} position={[0, 177, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[90, 90, 100]} />
      <mesh geometry={nodes.Cylinder002_Body_0.geometry} material={materials.Body} position={[0, 1078, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[95, 95, 14]} />
      <mesh geometry={nodes.Torus_Body_0.geometry} material={materials.Body} position={[0, 1238.45, 0]} rotation={[Math.PI, 0, 0]} scale={76} />
    </group>
  )
}

useGLTF.preload('/glowstick-transformed.glb')
