/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 helipad_circle.gltf --transform
Author: YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/helipad-dbf9832e36314438b94a2cc1b15a24c1
Title: Helipad
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HelipadCircle(props) {
  const { nodes, materials } = useGLTF('/helipad_circle-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={188.68}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0_1'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0_2'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0_3'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0_4'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0_5'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
            <mesh geometry={nodes['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan_0_6'].geometry} material={materials['Screenshot_2022-06-09_at_16-51-21_Wall_Mural_Helicopter_lan']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/helipad_circle-transformed.glb')
