/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 square.gltf --transform
Author: timtime (https://sketchfab.com/timtime)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/squid-game-sugar-honeycomb-square-cookie-03a821de277a4e21a3de7f9a2966e697
Title: Squid Game Sugar Honeycomb Square Cookie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/square-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.07, 1]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/square-transformed.glb')
