/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 plane_red.gltf --transform
Author: Arion Digital (https://sketchfab.com/andrewswihart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/airplane-white-and-red-742f06047a3d451e9c61951ef598c6ba
Title: Airplane - White and Red
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PlaneRed(props) {
  const { nodes, materials } = useGLTF('/plane_red-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.VLJ_FUS__CIRRUSTS19JPG_0.geometry} material={materials['FUS__CIRRUSTS19.JPG']} />
        <mesh geometry={nodes.GLASS_GLASS__CIRRUSTS19JPG_0.geometry} material={materials['GLASS__CIRRUSTS19.JPG']} />
      </group>
    </group>
  )
}

useGLTF.preload('/plane_red-transformed.glb')
