/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 square_frame.gltf --transform
Author: koinKangaroo (https://sketchfab.com/koinKangaroo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-square-frame-eca0dad45a8c4fcf91c8502f1bec4576
Title: 3D square Frame
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FrameBlock(props) {
  const { nodes, materials } = useGLTF('/square_frame-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/square_frame-transformed.glb')
