/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 airplane.gltf --transform
Author: Tomations (https://sketchfab.com/Tomations)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/airplane-98f903ce92a74216bba161068812bd5d
Title: Airplane
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/airplane-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group position={[0, 0, 0.36]}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Metal_PBR} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Metal_PBR.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/airplane-transformed.glb')
