/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lightbulb.gltf --transform
Author: ffffoooo (https://sketchfab.com/ffffoooo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/light-bulb-1bf43ed7628e48e7bceae6f6c5ac06d9
Title: Light-bulb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lightbulb(props) {
  const { nodes, materials } = useGLTF('/lightbulb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.surfaceShader1} position={[0, -10.16, -23.15]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.lambert2} position={[0, 0.46, -23.15]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.lambert3} position={[0, 0, -23.15]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.lambert3} position={[0, 0, -23.15]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.lambert3} position={[-1.2, -1.11, -23.15]} rotation={[0, 0, 0.33]} scale={[0.17, 0.1, 0.22]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.lambert3} position={[1.28, -1.11, -23.15]} rotation={[0, 0, -0.33]} scale={[-0.17, 0.1, 0.22]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.lambert3} position={[-0.57, 2.25, -23.15]} scale={[0.12, 0.09, 0.13]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.lambert3} position={[0.55, 2.25, -23.15]} scale={[-0.12, 0.09, 0.13]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.lambert1} position={[4.53, 4.26, -23.15]} rotation={[0, 0, -1.21]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/lightbulb-transformed.glb')
