/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 billboard2.gltf --transform
Author: daviddickball (https://sketchfab.com/daviddickball)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-low-poly-billboard-16-9-86c40bba17b843a090fb380e8b829eab
Title: Simple low-poly billboard (16-9)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Billboard2(props) {
  const { nodes, materials } = useGLTF('/billboard2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Frame_16-9_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[16.2, 6.48, -3.02]} />
      <mesh geometry={nodes['Board_16-9_Board_0'].geometry} material={materials.Board} position={[16.2, 6.48, -3.02]} />
    </group>
  )
}

useGLTF.preload('/billboard2-transformed.glb')
